### Import pandas and read in the csv file and set it to a dataframe called df

## Setting up python

In [25]:
import pandas as pd
import numpy as np
#import xml.etree.ElementTree as ET

In [26]:
import os
os.chdir('/Users/yingli/Development/TopicsInDataScience/topicsindatascience')
df = pd.read_csv('dhs_service_records_synthesized_final.csv')

## Conduct some simple data inspection

 - take a look at the first ten rows, and last 7 rows

In [27]:
df.head()

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
0,SYNTHETIC DATA,1626.0,2021.0,01/31/2021,Children_Attending_Early_Childhood_Programs_Ma...,NaN,5.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,9-12~High School (grade 9-12),NaN
1,SYNTHETIC DATA,1626.0,2021.0,02/28/2021,Children_Attending_Early_Childhood_Programs_Ma...,NaN,5.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,9-12~High School (grade 9-12),NaN
2,SYNTHETIC DATA,1626.0,2021.0,03/31/2021,Children_Attending_Early_Childhood_Programs_Ma...,NaN,5.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,9-12~High School (grade 9-12),NaN
3,SYNTHETIC DATA,1626.0,2021.0,04/30/2021,Children_Attending_Early_Childhood_Programs_Ma...,NaN,5.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,9-12~High School (grade 9-12),NaN
4,SYNTHETIC DATA,1626.0,2021.0,05/31/2021,Children_Attending_Early_Childhood_Programs_Ma...,NaN,5.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,99~Unknown,NaN,NaN,99~Unknown,9-12~High School (grade 9-12),NaN

In [28]:
df.tail(7)

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
5614907,SYNTHETIC DATA,457092.0,2021.0,10/31/2021,Individuals_Receiving_Income_Supports,NaN,27.0,NaN,NaN,1~Male,NaN,NaN,NaN,2~Black/African American,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,6-8~Middle School (Grade 6-8),NaN
5614908,SYNTHETIC DATA,457092.0,2021.0,11/30/2021,Individuals_Receiving_Income_Supports,NaN,27.0,NaN,NaN,1~Male,NaN,NaN,NaN,2~Black/African American,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,6-8~Middle School (Grade 6-8),NaN
5614909,SYNTHETIC DATA,457092.0,2021.0,12/31/2021,Individuals_Receiving_Income_Supports,NaN,27.0,NaN,NaN,1~Male,NaN,NaN,NaN,2~Black/African American,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,6-8~Middle School (Grade 6-8),NaN
5614910,SYNTHETIC DATA,457093.0,2021.0,01/31/2021,Individuals_Receiving_Income_Supports,NaN,52.0,NaN,NaN,1~Male,NaN,NaN,NaN,4~Asian,99~Unknown,NaN,NaN,2~Married,9-12~High School (grade 9-12),NaN
5614911,SYNTHETIC DATA,457093.0,2021.0,02/28/2021,Individuals_Receiving_Income_Supports,NaN,52.0,NaN,NaN,1~Male,NaN,NaN,NaN,4~Asian,99~Unknown,NaN,NaN,2~Married,9-12~High School (grade 9-12),NaN
5614912,SYNTHETIC DATA,457093.0,2021.0,03/31/2021,Individuals_Receiving_Income_Supports,NaN,52.0,NaN,NaN,1~Male,NaN,NaN,NaN,4~Asian,99~Unknown,NaN,NaN,2~Married,9-12~High School (grade 9-12),NaN
5614913,SYNTHET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Looks like the last row is completely NaN, also, has a different value for "synthetic_data".

### dataframe dimensions, column names, column data types, ranges of column values

In [29]:
df.shape

(5614914, 20)

In [30]:
df.columns

Index(['synthetic_data', 'MCI_UNIQ_ID', 'CALDR_YR', 'DATE_OF_EVENT', 'service',
       'GEO_AREA', 'age', 'DOB', 'DOD', 'GENDER', 'GENDER_IDENTITY',
       'SEX_ORIENT', 'LEGAL_SEX', 'RACE', 'ETHNICITY', 'LIVING_ARRANGEMENT',
       'EMPLOYMENT_STATUS', 'MARITAL_STATUS', 'EDUCATION_LEVEL',
       'VETERAN_FLAG'],
      dtype='object')

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5614914 entries, 0 to 5614913
Data columns (total 20 columns):
 #   Column              Dtype
---  ------              -----
 0   synthetic_data      object
 1   MCI_UNIQ_ID         float64
 2   CALDR_YR            float64
 3   DATE_OF_EVENT       object
 4   service             object
 5   GEO_AREA            float64
 6   age                 float64
 7   DOB                 float64
 8   DOD                 float64
 9   GENDER              object
 10  GENDER_IDENTITY     float64
 11  SEX_ORIENT          float64
 12  LEGAL_SEX           float64
 13  RACE                object
 14  ETHNICITY           object
 15  LIVING_ARRANGEMENT  float64
 16  EMPLOYMENT_STATUS   float64
 17  MARITAL_STATUS      object
 18  EDUCATION_LEVEL     object
 19  VETERAN_FLAG        float64
dtypes: float64(12), object(8)
memory usage: 856.8+ MB

 - another way to check the data types

In [32]:
df.dtypes

synthetic_data         object
MCI_UNIQ_ID           float64
CALDR_YR              float64
DATE_OF_EVENT          object
service                object
GEO_AREA              float64
age                   float64
DOB                   float64
DOD                   float64
GENDER                 object
GENDER_IDENTITY       float64
SEX_ORIENT            float64
LEGAL_SEX             float64
RACE                   object
ETHNICITY              object
LIVING_ARRANGEMENT    float64
EMPLOYMENT_STATUS     float64
MARITAL_STATUS         object
EDUCATION_LEVEL        object
VETERAN_FLAG          float64
dtype: object

In [33]:
df.nunique()

synthetic_data             2
MCI_UNIQ_ID           457952
CALDR_YR                   1
DATE_OF_EVENT             12
service                   12
GEO_AREA                   0
age                      110
DOB                        0
DOD                        0
GENDER                     3
GENDER_IDENTITY            0
SEX_ORIENT                 0
LEGAL_SEX                  0
RACE                       7
ETHNICITY                  3
LIVING_ARRANGEMENT         0
EMPLOYMENT_STATUS          0
MARITAL_STATUS             7
EDUCATION_LEVEL            8
VETERAN_FLAG               0
dtype: int64

In [34]:
df.groupby("synthetic_data").count()

,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
synthetic_data,,,,,,,,,,,,,,,,,,,
SYNTHET,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
SYNTHETIC DATA,5614913,5614913,5614913,5614913,0,5614913,0,0,5614913,0,0,0,5614913,5614913,0,0,5614913,5614913,0

In [35]:
df["synthetic_data"].value_counts()

synthetic_data
SYNTHETIC DATA    5614913
SYNTHET                 1
Name: count, dtype: int64

 - one way to get an overview of the data values

In [36]:
df.describe()

,MCI_UNIQ_ID,CALDR_YR,GEO_AREA,age,DOB,DOD,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,VETERAN_FLAG
count,5.614913e+06,5614913.0,0.0,5.614913e+06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mean,2.350944e+05,2021.0,NaN,3.148510e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,1.366866e+05,0.0,NaN,2.198595e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1.000000e+00,2021.0,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1.172170e+05,2021.0,NaN,1.300000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,2.343240e+05,2021.0,NaN,2.900000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,3.513950e+05,2021.0,NaN,4.700000e+01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,5.356070e+05,2021.0,NaN,1.210000e+02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

lots of NAs, so lets count the NA

In [37]:
df.shape

(5614914, 20)

In [38]:
df.isna().sum()

synthetic_data              0
MCI_UNIQ_ID                 1
CALDR_YR                    1
DATE_OF_EVENT               1
service                     1
GEO_AREA              5614914
age                         1
DOB                   5614914
DOD                   5614914
GENDER                      1
GENDER_IDENTITY       5614914
SEX_ORIENT            5614914
LEGAL_SEX             5614914
RACE                        1
ETHNICITY                   1
LIVING_ARRANGEMENT    5614914
EMPLOYMENT_STATUS     5614914
MARITAL_STATUS              1
EDUCATION_LEVEL             1
VETERAN_FLAG          5614914
dtype: int64

In [39]:
df.isnull().sum()

synthetic_data              0
MCI_UNIQ_ID                 1
CALDR_YR                    1
DATE_OF_EVENT               1
service                     1
GEO_AREA              5614914
age                         1
DOB                   5614914
DOD                   5614914
GENDER                      1
GENDER_IDENTITY       5614914
SEX_ORIENT            5614914
LEGAL_SEX             5614914
RACE                        1
ETHNICITY                   1
LIVING_ARRANGEMENT    5614914
EMPLOYMENT_STATUS     5614914
MARITAL_STATUS              1
EDUCATION_LEVEL             1
VETERAN_FLAG          5614914
dtype: int64

these columns have only NAs
['GEO_AREA', 'DOB', 'DOD', 'GENDER_IDENTITY', 'SEX_ORIENT', 'LEGAL_SEX', 'LIVING_ARRANGEMENT',
       'EMPLOYMENT_STATUS', 'VETERAN_FLAG']

and there seem to be one row that has NA in all columns? usually it can be the first row or last row. But let's verify.

In [40]:
df.isna().tail(1)

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
5614913,False,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

let's clean up the data frame then, drop last row, drop the columns that only have NAs

In [42]:
df.tail(1)

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
5614913,SYNTHET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df.dropna(how='all', inplace=True)
df.shape

(5614914, 20)

In [44]:
df.tail(1)

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
5614913,SYNTHET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

df.dropna(how="all") would not remove the last row, we need a way to drop the last row

In [45]:
# df.dropna(inplace=True) # will drop rows with any NA.

 - question: what can you observe from the above result?

 - take a look at 3 random rows, it is important to inspect data beyond the head and tail

In [18]:
# set seed for random function so that we get same rows when re-run the cell
np.random.seed(17)
np.random.randint(2, df.shape[0],3)

array([ 589043, 5539985, 2078088])

In [19]:
np.random.randint(3, df.shape[0],3)

array([491929, 828732, 776112])

In [20]:
# set seed for random function so that we get same rows when re-run the cell
np.random.seed(17)
df.iloc[np.random.randint(0, df.shape[0],3)]

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
589041,SYNTHETIC DATA,364757.0,2021.0,10/31/2021,Individuals_Receiving_DHS_Services,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
5539983,SYNTHETIC DATA,449747.0,2021.0,09/30/2021,Individuals_Receiving_Income_Supports,NaN,51.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
2078086,SYNTHETIC DATA,109525.0,2021.0,09/30/2021,Individuals_Receiving_Income_Supports,NaN,51.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN

 - take a look at the record for a specific MCI_UNIQ_ID, say merchant 364757 from above result

In [46]:
df[df['MCI_UNIQ_ID'] == 364757]

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
589034,SYNTHETIC DATA,364757.0,2021.0,02/28/2021,Individuals_Receiving_DHS_Services,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
589035,SYNTHETIC DATA,364757.0,2021.0,03/31/2021,Individuals_Receiving_DHS_Services,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
589036,SYNTHETIC DATA,364757.0,2021.0,05/31/2021,Individuals_Receiving_DHS_Services,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
589037,SYNTHETIC DATA,364757.0,2021.0,06/30/2021,Individuals_Receiving_DHS_Services,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
589038,SYNTHETIC DATA,364757.0,2021.0,07/31/2021,Individuals_Receiving_DHS_Services,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
589039,SYNTHETIC DATA,364757.0,2021.0,08/31/2021,Individuals_Receiving_DHS_Services,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
589040,SYNTHETIC DATA,364757.0,2021.0,09/30/2021,Individuals_Receiving_DHS_Services,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
589041,SYNTHETIC DATA,364757.0,2021.0,10/31/2021,Individuals_Receiving_DHS_Services,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
589042,SYNTHETIC DATA,364757.0,2021.0,11/30/2021,Individuals_Receiving_DHS_Services,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
589043,SYNTHETIC DATA,364757.0,2021.0,12/31/2021,Individuals_Receiving_DHS_Services,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
4675581,SYNTHETIC DATA,364757.0,2021.0,01/31/2021,Individuals_Receiving_Income_Supports,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
4675582,SYNTHETIC DATA,364757.0,2021.0,02/28/2021,Individuals_Receiving_Income_Supports,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
4675583,SYNTHETIC DATA,364757.0,2021.0,03/31/2021,Individuals_Receiving_Income_Supports,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
4675584,SYNTHETIC DATA,364757.0,2021.0,04/30/2021,Individuals_Receiving_Income_Supports,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
4675585,SYNTHETIC DATA,364757.0,2021.0,05/31/2021,Individuals_Receiving_Income_Supports,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
4675586,SYNTHETIC DATA,364757.0,2021.0,06/30/2021,Individuals_Receiving_Income_Supports,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
4675587,SYNTHETIC DATA,364757.0,2021.0,07/31/2021,Individuals_Receiving_Income_Supports,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
4675588,SYNTHETIC DATA,364757.0,2021.0,08/31/2021,Individuals_Receiving_Income_Supports,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
4675589,SYNTHETIC DATA,364757.0,2021.0,09/30/2021,Individuals_Receiving_Income_Supports,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
4675590,SYNTHETIC DATA,364757.0,2021.0,10/31/2021,Individuals_Receiving_Income_Supports,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
4675591,SYNTHETIC DATA,364757.0,2021.0,11/30/2021,Individuals_Receiving_Income_Supports,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
4675592,SYNTHETIC DATA,364757.0,2021.0,12/31/2021,Individuals_Receiving_Income_Supports,NaN,54.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN

In [47]:
df[df['MCI_UNIQ_ID'] == 449747]

,synthetic_data,MCI_UNIQ_ID,CALDR_YR,DATE_OF_EVENT,service,GEO_AREA,age,DOB,DOD,GENDER,GENDER_IDENTITY,SEX_ORIENT,LEGAL_SEX,RACE,ETHNICITY,LIVING_ARRANGEMENT,EMPLOYMENT_STATUS,MARITAL_STATUS,EDUCATION_LEVEL,VETERAN_FLAG
5539976,SYNTHETIC DATA,449747.0,2021.0,01/31/2021,Individuals_Receiving_Income_Supports,NaN,51.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
5539977,SYNTHETIC DATA,449747.0,2021.0,03/31/2021,Individuals_Receiving_Income_Supports,NaN,51.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
5539978,SYNTHETIC DATA,449747.0,2021.0,04/30/2021,Individuals_Receiving_Income_Supports,NaN,51.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
5539979,SYNTHETIC DATA,449747.0,2021.0,05/31/2021,Individuals_Receiving_Income_Supports,NaN,51.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
5539980,SYNTHETIC DATA,449747.0,2021.0,06/30/2021,Individuals_Receiving_Income_Supports,NaN,51.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
5539981,SYNTHETIC DATA,449747.0,2021.0,07/31/2021,Individuals_Receiving_Income_Supports,NaN,51.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
5539982,SYNTHETIC DATA,449747.0,2021.0,08/31/2021,Individuals_Receiving_Income_Supports,NaN,51.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
5539983,SYNTHETIC DATA,449747.0,2021.0,09/30/2021,Individuals_Receiving_Income_Supports,NaN,51.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
5539984,SYNTHETIC DATA,449747.0,2021.0,10/31/2021,Individuals_Receiving_Income_Supports,NaN,51.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN
5539985,SYNTHETIC DATA,449747.0,2021.0,11/30/2021,Individuals_Receiving_Income_Supports,NaN,51.0,NaN,NaN,1~Male,NaN,NaN,NaN,1~White,2~Not Hispanic/Latinx,NaN,NaN,1~Single-Never Married,99~Unknown,NaN

## Conduct some more data inspection at your own time

 - which MCI_UNIQ_ID has the highest number of records among all ID's
 - what is the average number of interactions for clients in the file?
 - how many months did a particular client use the service? say 449747
 - what can you observe from the data?

## gather all observations, questions, and TODOs

 - columns "DATE_OF_EVENT" is string type and should be date type
 - if we remove the last row, there would be only one value in the "synthetic_data" column, should we remove the column? 
 - MCI_UNIQ_ID column was read into dataframe as numeric, what should we read it in as?
 - do the statistics on the columns make sense? e.g., are there any inconsistencies between age and eduction level? 
 - how many clients used the services in January? How many clients used service by each month?
 - what is the average number of services a client use? 
 - how many clients receive services every month? 
 - do the number of services per client increase over time?

other data formats that we may teach, TBD

In [ ]:
df1 = pd.read_xml("/Users/yingli/Development/TopicsInDataScience/topicsindatascience/GrantsDBExtract20240618v2.xml")